version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/prod.dockerfile
    ports:
      - '3000:3000'
    networks:
      - vue_boilerplate

networks:
  vue_boilerplate:
    driver: bridge
